In [3]:
import tensorflow as tf
import keras as K
import numpy as np

Using TensorFlow backend.


In [11]:
def mse(y_true,y_pred):
    
    loss = tf.square(y_true-y_pred)
    return tf.reduce_sum(loss,axis=-1)

def bce(y_true,y_pred):
    y_pred = tf.math.sigmoid(y_pred)
    print("Loss",tf.shape(y_pred))
    y_pred = tf.maximum(y_pred, 1e-15)
    y_pred = tf.minimum(y_pred, 1-1e-15)
    loss = y_true*tf.math.log(y_pred) + (1-y_true)*tf.math.log(1-y_pred)
    print("Bce",tf.shape(loss))
    
    return -tf.reduce_sum(loss,axis=-1)

def Loss(y_true,y_pred):
    '''
    Arguments:
    
    y_true:Numpy array Ground truth prediction of the form (m,h1,w1,classes+5)
    y_pred: Tf tensor of same shape as y_true ;Output of model
    
    '''
    batch_size = tf.cast(tf.shape(y_pred)[0],dtype = tf.float32)
    
    lambda_coord = tf.constant(5.0)
    lambda_noobj = tf.constant(0.5)
    
    print("True",tf.shape(y_true))
    print("Pred",tf.shape(y_pred))
    obj_mask = tf.cast(tf.equal(y_true[...,4],1),dtype=tf.float32)
    ignore_mask = 1-tf.cast(tf.equal(y_true[...,4],-1),dtype=tf.float32)
    
    print("Masks",tf.shape(obj_mask),tf.shape(ignore_mask))
    loc_loss = lambda_coord*tf.cast(mse(y_true[:,:,:,0:4],y_pred[:,:,:,0:4]),dtype=tf.float32)*obj_mask
    
    obj_loss =  tf.cast(bce(y_true[:,:,:,4:5],y_pred[:,:,:,4:5]),dtype=tf.float32)*obj_mask
    no_obj_loss = tf.cast(bce(y_true[:,:,:,4:5],y_pred[:,:,:,4:5]),dtype=tf.float32)*(1-obj_mask)*ignore_mask*lambda_noobj
    class_loss = tf.cast(bce(y_true[:,:,:,5:],y_pred[:,:,:,5:]),dtype=tf.float32)*obj_mask
    
    
    total_loss = obj_loss + no_obj_loss + class_loss + loc_loss
    print("total",tf.shape(total_loss))
    
    return tf.reduce_sum(total_loss)    
    





  
    
    

In [13]:
Loss(tf.random.normal([32,12,16,9]),tf.random.normal([32,12,16,9],seed=2))
tf.random.normal([32,12,16,9])

True tf.Tensor([32 12 16  9], shape=(4,), dtype=int32)
Pred tf.Tensor([32 12 16  9], shape=(4,), dtype=int32)
Masks tf.Tensor([32 12 16], shape=(3,), dtype=int32) tf.Tensor([32 12 16], shape=(3,), dtype=int32)
Loss tf.Tensor([32 12 16  1], shape=(4,), dtype=int32)
Bce tf.Tensor([32 12 16  1], shape=(4,), dtype=int32)
Loss tf.Tensor([32 12 16  1], shape=(4,), dtype=int32)
Bce tf.Tensor([32 12 16  1], shape=(4,), dtype=int32)
Loss tf.Tensor([32 12 16  4], shape=(4,), dtype=int32)
Bce tf.Tensor([32 12 16  4], shape=(4,), dtype=int32)
total tf.Tensor([32 12 16], shape=(3,), dtype=int32)


<tf.Tensor: shape=(32, 12, 16, 9), dtype=float32, numpy=
array([[[[-5.99940956e-01, -5.56216776e-01,  8.24484050e-01, ...,
          -4.83658433e-01, -1.19583869e+00, -1.82478517e-01],
         [ 2.13754550e-02, -4.67960835e-02, -1.71669260e-01, ...,
           5.72766960e-01, -7.63734162e-01,  3.09581757e-01],
         [ 1.54161263e+00, -1.79307425e+00, -9.28605318e-01, ...,
          -1.85380614e+00, -4.21252251e-01,  9.31898236e-01],
         ...,
         [-1.22182459e-01,  1.44403124e+00, -1.28001976e+00, ...,
          -1.81617022e+00,  1.51779246e+00,  8.98509264e-01],
         [ 3.32590133e-01,  1.91003656e+00,  1.38148856e+00, ...,
           1.78533792e+00, -5.16873062e-01,  5.43552227e-02],
         [-3.49738955e-01,  1.16004229e+00,  8.12047541e-01, ...,
          -1.42991042e+00, -2.04616949e-01, -7.44424760e-01]],

        [[ 1.04951978e+00, -3.06929618e-01,  4.20704633e-02, ...,
           2.62050658e-01, -1.05874252e+00,  1.59699619e+00],
         [ 1.53530195e-01,  3.9

In [18]:
tf.math.sigmoid(tf.random.normal([2,2]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.90724975, 0.8209817 ],
       [0.49770993, 0.6544529 ]], dtype=float32)>